spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/social_manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres123}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  quartz:
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 10000
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}